on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aksregjulio.azurecr.io
        username: ${{ secrets.acr_aksregjulio_username }}
        password: ${{ secrets.acr_aksregjulio_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t aksregjulio.azurecr.io/overleaf:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push aksregjulio.azurecr.io/overleaf:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_overleaf_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep overleafb5fc | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace overleafb5fc`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: overleafb5fc
        container-registry-url: aksregjulio.azurecr.io
        container-registry-username: ${{ secrets.acr_aksregjulio_username }}
        container-registry-password: ${{ secrets.acr_aksregjulio_password }}
        secret-name: overleafdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: overleafb5fc
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          aksregjulio.azurecr.io/overleaf:${{ github.sha }}
        imagepullsecrets: |
          overleafdockerauth
